### ISSUE TITLE
HU07 - Crear un álbum

### ISSUE THREAD

**Issue by JuanDaCalderon** [JuanDaCalderon/vinilos_MISO_Moviles_4203#7]
Como coleccionista quiero agregar un álbum al listado

Como coleccionista quiero agregar un Álbum al listado 

![Image](https://github.com/JuanDaCalderon/vinilos_MISO_Moviles_4203/assets/71572762/74a5fc06-5a8b-4b78-8879-70ea9c16f70c)

CRITERIOS DE ACEPTACIÓN:

- Cuando oprima el botón  mas (+) en la parte superior de la card de listado de Álbumes debe ser capaz de llevarme al formulario de creación de un álbum nuevo 
- En el formulario debo poder escribir el Nombre del álbum 
- En el formulario debo poder escribir el Cover del álbum 
- En el formulario debo poder escribir la fecha de lanzamiento del álbum 
- En el formulario debo poder escribir el Generó del álbum 
- En el formulario debo poder escribir la Disquera  del álbum 
- En el formulario debo poder escribir una Descripción  del álbum 
- Cuando oprima el botón crear en la parte inferior del formulario debe crear el álbum nuevo y redirigirle a la lista de álbumes

SUB-TAREAS:

1. Identificar el endpoint que necesito por parte del backend para crear un álbum (1h)
2. Documentarme en Android studio (2h)
3. Desarrollar los modelos y clases para crea el álbum (2h)
4. Desarrollar la vista de la pantalla de crear album (2h)
5. Desarrollar la Card de crear album (2h)
7. Desarrollar la logica de crear album (3h)

**Comment by lacortesz** [comment]
- Crear pantalla principal
